from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one match in {path}, found {count}")
    p.write_text(text.replace(old, new, 1))


path = "aqorath/web_assets.py"
old_html = '''<pre id="reportOutput">Aún no has generado un reporte.</pre></div>
</div></section>
'''
new_html = '''<pre id="reportOutput">Aún no has generado un reporte.</pre></div>
<div class="card span12" id="reportPresetFlow"><h2>Mis paquetes de reportes</h2><p class="muted">Guarda una selección y su orden para volver a generar los reportes con cifras actuales. El paquete no guarda saldos ni resultados.</p><div class="toolbar"><div><label for="reportPresetSaved">Paquete guardado</label><select id="reportPresetSaved"><option value="">Nuevo paquete</option></select></div><button class="secondary" id="reportPresetLoad">Cargar</button><button class="secondary" id="reportPresetNew">Nuevo</button><div><label for="reportPresetName">Nombre</label><input id="reportPresetName" placeholder="Consejo mensual"></div><div><label for="reportPresetFormat">Formato</label><select id="reportPresetFormat"><option value="json">Vista en pantalla</option><option value="xlsx">Excel</option></select></div></div><div class="toolbar"><div><label for="reportPresetAvailable">Agregar reporte</label><select id="reportPresetAvailable"></select></div><button class="secondary" id="reportPresetAdd">Agregar</button></div><div id="reportPresetItems" class="notice"><span class="muted">Agrega los reportes en el orden deseado.</span></div><div class="toolbar"><div><label for="reportPresetFrom">Desde</label><input id="reportPresetFrom" type="date"></div><div><label for="reportPresetTo">Hasta / fecha de corte</label><input id="reportPresetTo" type="date"></div></div><div class="actions"><button class="primary" id="reportPresetSave">Guardar paquete</button><button class="primary" id="reportPresetExecute">Generar paquete</button><button class="secondary" id="reportPresetProfessional">Ver trazabilidad profesional</button><button class="danger hidden" id="reportPresetDelete">Eliminar paquete</button><button class="secondary hidden" id="reportPresetDownload">Descargar Excel</button></div><div id="reportPresetError" class="notice error hidden"></div><pre id="reportPresetOutput">Aún no has generado este paquete.</pre></div>
</div></section>
'''
replace_once(path, old_html, new_html)

old_js = '''initReporting().catch(e=>showError('reportError',e));
init().catch(e=>showError('commonError',e));
'''
new_js = r'''initReporting().catch(e=>showError('reportError',e));
const presetState={id:null,reports:[],catalog:[],dimensions:[],download:null};
function presetDefinition(id){return presetState.catalog.find(item=>item.id===Number(id))}
function presetCommonFormats(){if(!presetState.reports.length)return['json','xlsx'];let formats=[...presetDefinition(presetState.reports[0].definition_id).supported_formats];for(const item of presetState.reports.slice(1)){const allowed=new Set(presetDefinition(item.definition_id).supported_formats);formats=formats.filter(value=>allowed.has(value))}return formats}
function renderPresetFormat(){const formats=presetCommonFormats();const current=$('reportPresetFormat').value;$('reportPresetFormat').innerHTML=formats.map(value=>`<option value="${esc(value)}">${value==='xlsx'?'Excel':'Vista en pantalla'}</option>`).join('');if(formats.includes(current))$('reportPresetFormat').value=current}
function renderPresetItems(){if(!presetState.reports.length){$('reportPresetItems').innerHTML='<span class="muted">Agrega los reportes en el orden deseado.</span>';renderPresetFormat();return}$('reportPresetItems').innerHTML=presetState.reports.map((item,index)=>{const definition=presetDefinition(item.definition_id);const analytical=definition&&definition.key==='analytical.activity.period';const dimension=analytical?`<select data-preset-dimension="${index}">${presetState.dimensions.map(d=>`<option value="${esc(d.key)}" ${item.parameters.dimension_key===d.key?'selected':''}>${esc(d.name)}</option>`).join('')}</select>`:'';return`<div class="toolbar" style="margin-bottom:8px"><div><b>${index+1}. ${esc(definition?definition.name:String(item.definition_id))}</b>${analytical?'<div class="small muted">Dimensión</div>'+dimension:''}</div><button class="secondary" data-preset-up="${index}" ${index===0?'disabled':''}>↑</button><button class="secondary" data-preset-down="${index}" ${index===presetState.reports.length-1?'disabled':''}>↓</button><button class="danger" data-preset-remove="${index}">Quitar</button></div>`}).join('');$('reportPresetItems').querySelectorAll('[data-preset-up]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.presetUp);[presetState.reports[i-1],presetState.reports[i]]=[presetState.reports[i],presetState.reports[i-1]];renderPresetItems()});$('reportPresetItems').querySelectorAll('[data-preset-down]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.presetDown);[presetState.reports[i+1],presetState.reports[i]]=[presetState.reports[i],presetState.reports[i+1]];renderPresetItems()});$('reportPresetItems').querySelectorAll('[data-preset-remove]').forEach(button=>button.onclick=()=>{presetState.reports.splice(Number(button.dataset.presetRemove),1);renderPresetItems()});$('reportPresetItems').querySelectorAll('[data-preset-dimension]').forEach(select=>select.onchange=()=>{presetState.reports[Number(select.dataset.presetDimension)].parameters.dimension_key=select.value});renderPresetFormat()}
function resetPreset(){presetState.id=null;presetState.reports=[];$('reportPresetSaved').value='';$('reportPresetName').value='';$('reportPresetDelete').classList.add('hidden');$('reportPresetOutput').textContent='Aún no has generado este paquete.';$('reportPresetDownload').classList.add('hidden');presetState.download=null;renderPresetItems()}
async function refreshPresetList(){const rows=await api('/api/reports/presets');const selected=presetState.id===null?'':String(presetState.id);$('reportPresetSaved').innerHTML='<option value="">Nuevo paquete</option>'+rows.map(row=>`<option value="${row.id}">${esc(row.name)}</option>`).join('');$('reportPresetSaved').value=selected}
async function loadPreset(id){const value=await api('/api/reports/presets/'+encodeURIComponent(id));presetState.id=value.id;presetState.reports=value.reports.map(item=>({definition_id:item.definition_id,parameters:{...(item.parameters||{})}}));$('reportPresetName').value=value.name;$('reportPresetFormat').value=value.format;$('reportPresetSaved').value=String(value.id);$('reportPresetDelete').classList.remove('hidden');renderPresetItems();$('reportPresetFormat').value=value.format}
function presetSavePayload(){return{name:$('reportPresetName').value,format:$('reportPresetFormat').value,reports:presetState.reports.map(item=>({definition_id:item.definition_id,parameters:{...item.parameters}}))}}
async function initPresetEditor(){const today=new Date().toISOString().slice(0,10);$('reportPresetFrom').value=today;$('reportPresetTo').value=today;const [catalog,dimensions]=await Promise.all([api('/api/reports/catalog'),api('/api/reports/dimensions')]);presetState.catalog=catalog.definitions;presetState.dimensions=dimensions;$('reportPresetAvailable').innerHTML=presetState.catalog.map(item=>`<option value="${item.id}">${esc(item.name)}</option>`).join('');await refreshPresetList();resetPreset()}
$('reportPresetNew').onclick=resetPreset;$('reportPresetLoad').onclick=async()=>{clearError('reportPresetError');try{if(!$('reportPresetSaved').value)return resetPreset();await loadPreset($('reportPresetSaved').value)}catch(e){showError('reportPresetError',e)}};$('reportPresetAdd').onclick=()=>{const id=Number($('reportPresetAvailable').value);if(presetState.reports.some(item=>item.definition_id===id))return showError('reportPresetError',new Error('Ese reporte ya está incluido.'));const definition=presetDefinition(id);const parameters={};if(definition&&definition.key==='analytical.activity.period'){if(!presetState.dimensions.length)return showError('reportPresetError',new Error('No hay dimensiones configuradas para ese reporte.'));parameters.dimension_key=presetState.dimensions[0].key}presetState.reports.push({definition_id:id,parameters});clearError('reportPresetError');renderPresetItems()};
$('reportPresetSave').onclick=async()=>{clearError('reportPresetError');try{const payload=presetSavePayload();const path=presetState.id===null?'/api/reports/presets':'/api/reports/presets/'+encodeURIComponent(presetState.id);const out=await api(path,{method:presetState.id===null?'POST':'PUT',body:JSON.stringify(payload)});presetState.id=out.id;await refreshPresetList();await loadPreset(out.id);$('reportPresetOutput').textContent='Paquete guardado. Sólo se conservó su configuración.'}catch(e){showError('reportPresetError',e)}};
$('reportPresetDelete').onclick=async()=>{clearError('reportPresetError');try{if(presetState.id===null)return;await api('/api/reports/presets/'+encodeURIComponent(presetState.id),{method:'DELETE'});resetPreset();await refreshPresetList()}catch(e){showError('reportPresetError',e)}};
$('reportPresetExecute').onclick=async()=>{clearError('reportPresetError');try{if(presetState.id===null)throw new Error('Guarda el paquete antes de generarlo.');const payload={from_date:$('reportPresetFrom').value,to_date:$('reportPresetTo').value};const out=await api('/api/reports/presets/'+encodeURIComponent(presetState.id)+'/execute',{method:'POST',body:JSON.stringify(payload)});presetState.download=out.document_base64?{bytes:b64bytes(out.document_base64),media:out.media_type}:null;$('reportPresetDownload').classList.toggle('hidden',!presetState.download);const shown={...out};delete shown.document_base64;$('reportPresetOutput').textContent=JSON.stringify(shown,null,2)}catch(e){showError('reportPresetError',e)}};
$('reportPresetProfessional').onclick=async()=>{clearError('reportPresetError');try{if(presetState.id===null)throw new Error('Guarda el paquete antes de revisar su trazabilidad.');const payload={from_date:$('reportPresetFrom').value,to_date:$('reportPresetTo').value};const out=await api('/api/reports/presets/'+encodeURIComponent(presetState.id)+'/professional',{method:'POST',body:JSON.stringify(payload)});$('professionalReportOutput').textContent=JSON.stringify(out,null,2);document.querySelector('[data-view="professional"]').click()}catch(e){showError('reportPresetError',e)}};
$('reportPresetDownload').onclick=()=>{if(!presetState.download)return;const blob=new Blob([presetState.download.bytes],{type:presetState.download.media});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aqorath-paquete-reportes.xlsx';a.click();URL.revokeObjectURL(url)};
initPresetEditor().catch(e=>showError('reportPresetError',e));
init().catch(e=>showError('commonError',e));
'''
replace_once(path, old_js, new_js)
print("persisted preset UI editor applied")
