"""Self-contained browser shell for the local AQR-005 surface.

No template engine is required. The browser receives only presentation contracts;
accounting rules remain entirely server-side in Application.
"""

APP_HTML = r'''<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Aqorath</title>
<style>
:root{--ink:#17211f;--muted:#64706d;--line:#d9dfdd;--paper:#f5f7f6;--card:#fff;--accent:#1f5148;--soft:#e9f0ee;--danger:#8a2f2f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{background:var(--accent);color:white;padding:22px 28px}header h1{margin:0;font-size:25px;letter-spacing:.02em}header p{margin:4px 0 0;opacity:.82}main{max-width:1120px;margin:0 auto;padding:24px}.tabs{display:flex;gap:8px;margin-bottom:18px}.tab{border:1px solid var(--line);background:white;border-radius:8px;padding:9px 14px;cursor:pointer}.tab.active{background:var(--ink);border-color:var(--ink);color:white}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 1px 2px #00000008}.span7{grid-column:span 7}.span5{grid-column:span 5}.span12{grid-column:span 12}h2,h3{margin-top:0}label{display:block;font-weight:650;margin:12px 0 5px}input,select,button{font:inherit}input,select{width:100%;padding:10px 11px;border:1px solid #bcc6c3;border-radius:8px;background:white}button.primary,button.secondary,button.danger,.linkbutton{border:0;border-radius:8px;padding:10px 14px;cursor:pointer}.primary{background:var(--accent);color:white}.secondary{background:var(--soft);color:var(--ink)}.danger{background:#f5e7e7;color:var(--danger)}.linkbutton{background:transparent;color:var(--accent);padding:2px 0;text-decoration:underline}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}.muted{color:var(--muted)}.notice{padding:11px 13px;border-radius:8px;background:var(--soft);margin:10px 0}.error{background:#f7e8e8;color:var(--danger)}.hidden{display:none!important}.metric{display:inline-block;margin:4px 8px 4px 0;padding:5px 8px;background:var(--soft);border-radius:7px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line);vertical-align:top}th.num,td.num{text-align:right;font-variant-numeric:tabular-nums}code,pre{font:12.5px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}pre{background:#f1f4f3;padding:12px;border-radius:8px;overflow:auto;max-height:300px}.toolbar{display:flex;gap:8px;align-items:end}.toolbar>div{flex:1}.toolbar button{margin-bottom:1px}.status{font-weight:650}.small{font-size:13px}@media(max-width:780px){.span7,.span5,.span12{grid-column:span 12}.toolbar{display:block}.toolbar button{margin-top:10px}}
</style>
</head>
<body>
<header><h1>Aqorath</h1><p id="entityLabel">Contabilidad local · cargando entidad…</p></header>
<main>
<div class="tabs"><button class="tab active" data-view="common">Vista común</button><button class="tab" data-view="professional">Vista profesional</button></div>
<section id="common" class="view active">
<div class="grid">
<div class="card span7"><h2>Registrar un hecho económico</h2><p class="muted">Describe qué ocurrió. Aqorath determina la representación contable.</p>
<label for="operation">¿Qué ocurrió?</label><select id="operation"></select>
<label for="amount">Importe</label><input id="amount" inputmode="decimal" placeholder="0.00" autocomplete="off">
<label for="postingDate">Fecha</label><input id="postingDate" type="date">
<div class="actions"><button class="primary" id="prepareButton">Revisar antes de contabilizar</button></div><div id="commonError" class="notice error hidden"></div></div>
<div class="card span5"><h2>Decisión preparada</h2><div id="emptyPreview" class="muted">Aún no hay una operación preparada.</div><div id="preview" class="hidden"><div class="metric" id="previewOperation"></div><div class="metric" id="previewAmount"></div><div class="metric" id="previewDate"></div><p id="previewExplanation"></p><p class="small muted">Nada se contabiliza hasta confirmar esta decisión exacta.</p><div class="actions"><button class="primary" id="confirmButton">Confirmar y contabilizar</button><button class="danger" id="cancelButton">Cancelar</button></div></div><div id="postedNotice" class="notice hidden"></div></div>
<div class="card span12"><h2>Clientes y proveedores</h2>
<div class="toolbar"><div><label for="partyName">Nombre del tercero</label><input id="partyName"></div><div><label for="partyType">Relación</label><select id="partyType"><option value="customer">Cliente</option><option value="supplier">Proveedor</option><option value="other">Otro</option></select></div><button class="secondary" id="createParty">Guardar tercero</button></div>
<div id="partyNotice" class="notice hidden"></div></div>
<div class="card span12"><h2>Venta o compra a crédito</h2><p class="muted">Compras de servicios/gastos soportados. Mercancías y activos se incorporan en sus módulos correspondientes.</p>
<div class="toolbar"><div><label for="creditKind">¿Qué ocurrió?</label><select id="creditKind"><option value="sale_credit">Venta a crédito</option><option value="utility_credit">Compra de servicios a crédito</option></select></div><div><label for="creditParty">¿Con quién?</label><select id="creditParty"></select></div></div>
<div class="toolbar"><div><label for="creditAmount">Importe</label><input id="creditAmount" inputmode="decimal"></div><div><label for="creditDate">Fecha</label><input id="creditDate" type="date"></div><div><label for="dueDate">Vencimiento</label><input id="dueDate" type="date"></div></div>
<div class="toolbar"><div><label for="creditDocument">Folio del documento</label><input id="creditDocument"></div><div><label for="creditDocumentDate">Fecha del documento</label><input id="creditDocumentDate" type="date"></div><button class="primary" id="prepareCredit">Revisar operación a crédito</button></div></div>
<div class="card span12"><h2>Lo que te deben y lo que debes</h2>
<div class="toolbar"><div><label for="itemKind">Consultar</label><select id="itemKind"><option value="receivable">Lo que me deben</option><option value="payable">Lo que debo</option></select></div><div><label for="itemDate">Consultar al</label><input id="itemDate" type="date"></div><button class="secondary" id="refreshItems">Actualizar obligaciones</button></div>
<div id="reconciliationNotice" class="notice"></div><div style="overflow:auto"><table><thead><tr><th>Tercero / documento</th><th>Vencimiento</th><th>Estado</th><th>Saldo pendiente</th><th>Importe a cobrar/pagar</th><th>Acciones</th></tr></thead><tbody id="itemsBody"></tbody></table></div>
<h3 style="margin-top:20px">Un cobro o pago para las obligaciones elegidas</h3><p class="muted">Escribe el importe junto a cada obligación del mismo tercero. Para liquidarla, usa «Saldo completo». Deja vacías las demás.</p>
<div class="toolbar"><div><label for="paymentDate">Fecha del cobro/pago</label><input id="paymentDate" type="date"></div><div><label for="paymentDocument">Folio del comprobante</label><input id="paymentDocument"></div><div><label for="paymentDocumentDate">Fecha del comprobante</label><input id="paymentDocumentDate" type="date"></div><button class="primary" id="preparePayment">Revisar cobro/pago</button></div>
<div id="itemDetails"></div></div>
<div class="card span12 hidden" id="subledgerPreview"><h2>Revisar y confirmar</h2><div id="subledgerSummary"></div><div class="actions"><button class="primary" id="confirmSubledger">Confirmar operación</button><button class="secondary" id="cancelSubledger">Cancelar</button></div></div>
<div class="card span12 hidden" id="reversalForm"><h2>Revertir operación</h2><p>Se revertirá el cobro/pago completo, incluidas todas sus aplicaciones. La historia se conserva y las obligaciones se reabren.</p><label for="reversalReason">Motivo</label><input id="reversalReason"><label for="reversalDate">Fecha de reversión</label><input id="reversalDate" type="date"><button class="danger" id="confirmReversal">Confirmar reversión</button><button class="secondary" id="cancelReversal">Cancelar</button></div>
<div id="subledgerError" class="notice error hidden span12" role="alert"></div>
</div></section>
<section id="professional" class="view">
<div class="grid">
<div class="card span12"><h2>Inspección profesional</h2><div class="toolbar"><div><label for="entryId">ID de póliza</label><input id="entryId" inputmode="numeric" placeholder="Ej. 12"></div><button class="primary" id="loadEntryButton">Cargar póliza</button><button class="secondary" id="loadLastButton">Última confirmada</button></div><div id="professionalError" class="notice error hidden"></div></div>
<div class="card span12"><div class="toolbar"><div><h3>Diario reciente</h3><p class="muted small">Índice leído directamente del ledger; no es una copia paralela.</p></div><button class="secondary" id="refreshRecentButton">Actualizar</button></div><div style="overflow:auto"><table><thead><tr><th>Póliza</th><th>Fecha</th><th>Concepto</th><th>Período</th><th>Estado</th></tr></thead><tbody id="recentBody"><tr><td colspan="5" class="muted">Cargando…</td></tr></tbody></table></div></div>
<div id="professionalContent" class="span12 hidden grid">
<div class="card span5"><h3>Póliza y período</h3><div id="entryMeta"></div></div>
<div class="card span7"><h3>Trazabilidad</h3><div id="traceMeta"></div></div>
<div class="card span12"><h3>Cuentas · cargos y abonos</h3><div style="overflow:auto"><table><thead><tr><th>Cuenta</th><th>Nombre</th><th class="num">Debe</th><th class="num">Haber</th></tr></thead><tbody id="linesBody"></tbody></table></div></div>
<div class="card span7"><h3>Documentos y referencias</h3><div id="documents"></div></div>
<div class="card span5"><h3>Fiscalidad</h3><div id="fiscal"></div></div>
</div>
<div class="card span12"><h2>Submayor por tercero y documento</h2><div class="toolbar"><div><label for="proItemId">ID de obligación</label><input id="proItemId" inputmode="numeric"></div><div><label for="proAsOf">Fecha de corte / aging</label><input id="proAsOf" type="date"></div><button class="primary" id="inspectItem">Inspeccionar obligación</button></div><div id="proItemOutput"></div>
<div class="toolbar"><div><label for="proKind">Reconciliación</label><select id="proKind"><option value="receivable">Cuentas por cobrar</option><option value="payable">Cuentas por pagar</option></select></div><button class="secondary" id="reconcileButton">Consultar reconciliación</button></div><pre id="reconcileOutput"></pre></div>
<div class="card span12"><h3>Balanza desde la autoridad contable</h3><div class="toolbar"><div><label for="balanceDate">Fecha de corte (opcional)</label><input id="balanceDate" type="date"></div><button class="secondary" id="balanceButton">Consultar balanza</button></div><pre id="balanceOutput">Sin consulta.</pre></div>
</div></section>
</main>
<script>
const state={token:null,lastEntry:null};const $=id=>document.getElementById(id);function showError(id,e){const n=$(id);n.textContent=e?.message||String(e);n.classList.remove('hidden')}function clearError(id){$(id).classList.add('hidden')}async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});let body=null;try{body=await r.json()}catch{body={detail:await r.text()}}if(!r.ok)throw new Error(body.detail||'Error de operación');return body}function money(v){return v??'0'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');if(b.dataset.view==='professional')loadRecent()});
async function init(){const cap=await api('/api/capabilities');$('operation').innerHTML=cap.operations.map(x=>`<option value="${x.key}">${x.label}</option>`).join('');$('entityLabel').textContent=cap.entity?`${cap.entity.name}${cap.entity.rfc?' · '+cap.entity.rfc:''} · datos locales`:'Configuración de entidad pendiente · datos locales';$('postingDate').value=new Date().toISOString().slice(0,10);await loadRecent()}
$('prepareButton').onclick=async()=>{clearError('commonError');try{const out=await api('/api/operations/prepare',{method:'POST',body:JSON.stringify({operation_key:$('operation').value,amount:$('amount').value,posting_date:$('postingDate').value})});state.token=out.token;$('previewOperation').textContent=out.preview.operation;$('previewAmount').textContent='$ '+out.preview.amount;$('previewDate').textContent=out.preview.posting_date;$('previewExplanation').textContent=out.preview.explanation;$('emptyPreview').classList.add('hidden');$('preview').classList.remove('hidden');$('postedNotice').classList.add('hidden')}catch(e){showError('commonError',e)}};
$('cancelButton').onclick=async()=>{if(!state.token)return;try{await api('/api/operations/'+encodeURIComponent(state.token),{method:'DELETE'});state.token=null;$('preview').classList.add('hidden');$('emptyPreview').classList.remove('hidden')}catch(e){showError('commonError',e)}};
$('confirmButton').onclick=async()=>{if(!state.token)return;clearError('commonError');try{const out=await api('/api/operations/'+encodeURIComponent(state.token)+'/confirm',{method:'POST'});state.lastEntry=out.entry_id;state.token=null;$('preview').classList.add('hidden');$('emptyPreview').classList.remove('hidden');$('postedNotice').textContent=`Póliza ${out.entry_id} contabilizada y auditada.`;$('postedNotice').classList.remove('hidden');$('entryId').value=out.entry_id;await loadRecent()}catch(e){showError('commonError',e)}};
async function loadRecent(){try{const rows=await api('/api/professional/operations?limit=50');$('recentBody').innerHTML=rows.length?rows.map(r=>`<tr><td><button class="linkbutton" data-entry="${r.entry_id}">#${r.entry_id}</button></td><td>${r.posting_date}</td><td>${esc(r.concept||'')}</td><td>${r.period_id??''}</td><td>${r.state}</td></tr>`).join(''):'<tr><td colspan="5" class="muted">No hay pólizas.</td></tr>';$('recentBody').querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{const id=b.dataset.entry;$('entryId').value=id;loadEntry(id)})}catch(e){showError('professionalError',e)}}
function renderEntry(v){$('professionalContent').classList.remove('hidden');$('entryMeta').innerHTML=`<div class="metric">#${v.entry_id}</div><div class="metric status">${v.state}</div><p><b>Fecha:</b> ${v.posting_date}<br><b>Período:</b> ${v.period.id} (${v.period.year}-${String(v.period.month).padStart(2,'0')}) · ${v.period.state}<br><b>Ejercicio:</b> ${v.period.fiscal_year_state}</p><p>${esc(v.concept)}</p>`;$('linesBody').innerHTML=v.lines.map(l=>`<tr><td><code>${esc(l.account_code)}</code></td><td>${esc(l.account_name)}</td><td class="num">${money(l.debit)}</td><td class="num">${money(l.credit)}</td></tr>`).join('');$('documents').innerHTML=v.documents.length?v.documents.map(d=>`<p><b>${esc(d.document_type)}</b> · ${esc(d.document_number)}<br><span class="muted">${esc(d.issuer_name||'')} ${d.date} · ${d.is_validated?'validado':'sin validar'}</span></p>`).join(''):'<p class="muted">Sin documentos vinculados.</p>';$('traceMeta').innerHTML=`<p><b>Auditoría:</b> ${v.audit?`evento #${v.audit.id} · ${v.audit.event_type}`:'sin AuditEvent general histórico'}</p><p><b>Reversión:</b> ${v.reversal?`original ${v.reversal.original_entry_id} → reversión ${v.reversal.reversal_entry_id} · ${esc(v.reversal.reason)}`:'sin relación de reversión'}</p>${v.audit?`<details><summary>Detalle del evento</summary><pre>${esc(JSON.stringify(v.audit.details,null,2))}</pre></details>`:''}`;$('fiscal').innerHTML=v.fiscal_audit?`<p><b>${v.fiscal_audit.jurisdiction}</b> · ${v.fiscal_audit.regime}</p><p>${v.fiscal_audit.effects.length} efecto(s) fiscal(es) auditado(s).</p><details><summary>Proveniencia fiscal</summary><pre>${esc(JSON.stringify(v.fiscal_audit,null,2))}</pre></details>`:'<p class="muted">Esta póliza no tiene auditoría fiscalizada asociada.</p>'}
async function loadEntry(id){clearError('professionalError');try{const v=await api('/api/operations/'+encodeURIComponent(id)+'/professional');renderEntry(v)}catch(e){showError('professionalError',e)}}
$('loadEntryButton').onclick=()=>loadEntry($('entryId').value);$('loadLastButton').onclick=()=>{if(state.lastEntry){$('entryId').value=state.lastEntry;loadEntry(state.lastEntry)}else showError('professionalError',new Error('Aún no hay una póliza confirmada en esta sesión.'))};$('refreshRecentButton').onclick=loadRecent;$('balanceButton').onclick=async()=>{clearError('professionalError');try{const q=$('balanceDate').value?'?as_of='+encodeURIComponent($('balanceDate').value):'';const v=await api('/api/trial-balance'+q);$('balanceOutput').textContent=JSON.stringify(v,null,2)}catch(e){showError('professionalError',e)}};
init().catch(e=>showError('commonError',e));

const subledgerState={token:null,reversalEntry:null};
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const statusLabel=v=>({open:'Pendiente',settled:'Liquidada',cancelled:'Cancelada'}[v]||v);
async function loadParties(){const rows=await api('/api/subledger/third-parties');$('creditParty').innerHTML=rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
$('createParty').onclick=async()=>{clearError('subledgerError');try{const p=await api('/api/subledger/third-parties',{method:'POST',body:JSON.stringify({name:$('partyName').value,party_type:$('partyType').value})});await loadParties();$('creditParty').value=p.id;$('partyNotice').textContent=`${p.name} guardado.`;$('partyNotice').classList.remove('hidden')}catch(e){showError('subledgerError',e)}};
async function prepareSubledger(path,payload){clearError('subledgerError');try{if(subledgerState.token)await api('/api/operations/'+encodeURIComponent(subledgerState.token),{method:'DELETE'});subledgerState.token=null;const out=await api(path,{method:'POST',body:JSON.stringify(payload)});subledgerState.token=out.token;const v=out.preview;$('subledgerSummary').innerHTML=`<h3>${esc(v.operation)}</h3><p>${esc(v.third_party_name)} · ${esc(v.posting_date)} · Importe: ${esc(v.amount)}</p><p>Documento: ${esc(v.document_number)}${v.due_date?' · Vence: '+esc(v.due_date):''}</p>${(v.allocations||[]).map(a=>`<p>${esc(a.document_origin)} · Aplicar ${esc(a.amount)} · Pendiente antes: ${esc(a.open_balance_before)}</p>`).join('')}<p>${esc(v.explanation)}</p>`;$('subledgerPreview').classList.remove('hidden');$('subledgerPreview').scrollIntoView({block:'center'})}catch(e){showError('subledgerError',e)}}
$('prepareCredit').onclick=()=>prepareSubledger('/api/subledger/origins/prepare',{operation_key:$('creditKind').value,amount:$('creditAmount').value,posting_date:$('creditDate').value,third_party_id:Number($('creditParty').value),due_date:$('dueDate').value,document_type:'invoice',document_number:$('creditDocument').value,document_date:$('creditDocumentDate').value});
$('preparePayment').onclick=()=>prepareSubledger('/api/subledger/applications/batch/prepare',{allocations:Array.from(document.querySelectorAll('[data-allocation]')).filter(x=>x.value.trim()!=='').map(x=>({open_item_id:Number(x.dataset.allocation),amount:x.value})),posting_date:$('paymentDate').value,document_type:'payment',document_number:$('paymentDocument').value,document_date:$('paymentDocumentDate').value});
$('cancelSubledger').onclick=async()=>{try{if(subledgerState.token)await api('/api/operations/'+encodeURIComponent(subledgerState.token),{method:'DELETE'});subledgerState.token=null;$('subledgerPreview').classList.add('hidden')}catch(e){showError('subledgerError',e)}};
$('confirmSubledger').onclick=async()=>{if(!subledgerState.token)return;$('confirmSubledger').disabled=true;try{const out=await api('/api/operations/'+encodeURIComponent(subledgerState.token)+'/confirm',{method:'POST'});subledgerState.token=null;state.lastEntry=out.entry_id;$('entryId').value=out.entry_id;$('subledgerPreview').classList.add('hidden');await loadItems();await loadRecent()}catch(e){showError('subledgerError',e)}finally{$('confirmSubledger').disabled=false}};
async function loadItems(){clearError('subledgerError');try{const q='?kind='+$('itemKind').value+'&as_of='+$('itemDate').value;const rows=await api('/api/subledger/open-items'+q);$('itemsBody').innerHTML=rows.map(i=>`<tr><td>${esc(i.third_party_name)}<br>${esc(i.document_number)}</td><td>${esc(i.due_date)}</td><td>${esc(statusLabel(i.status))}</td><td>${esc(i.open_balance)}</td><td>${i.status==='open'?`<input aria-label="Aplicar a ${esc(i.document_number)}" data-allocation="${i.id}" inputmode="decimal"><button class="linkbutton" data-full="${i.id}" data-balance="${esc(i.open_balance)}">Saldo completo</button>`:''}</td><td><button class="linkbutton" data-detail="${i.id}">Detalle #${i.id}</button></td></tr>`).join('')||'<tr><td colspan="6">Sin obligaciones a esta fecha.</td></tr>';$('itemsBody').querySelectorAll('[data-full]').forEach(b=>b.onclick=()=>document.querySelector(`[data-allocation="${b.dataset.full}"]`).value=b.dataset.balance);$('itemsBody').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showItem(b.dataset.detail));const r=await api('/api/subledger/reconciliation/'+$('itemKind').value+'?as_of='+$('itemDate').value);$('reconciliationNotice').textContent=r.is_reconciled?'Obligaciones y movimientos contables conciliados.':`Hay movimientos sin asignar o diferencias que requieren revisión profesional. Diferencia: ${r.difference}. Movimientos: ${r.unassigned_line_ids.join(', ')}.`;$('reconciliationNotice').classList.toggle('error',!r.is_reconciled)}catch(e){showError('subledgerError',e)}}
function bindReversals(container){container.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>{subledgerState.reversalEntry=Number(b.dataset.reverse);$('reversalForm').classList.remove('hidden');document.querySelector('[data-view="common"]').click();$('reversalForm').scrollIntoView({block:'center'})})}
async function showItem(id){try{const i=await api('/api/subledger/open-items/'+id+'?as_of='+$('itemDate').value);$('proItemId').value=i.id;$('itemDetails').innerHTML=`<h3>${esc(i.document_number)} · ${esc(i.third_party_name)}</h3><p>Original: ${esc(i.original_amount)} · Aplicado: ${esc(i.applied_amount)} · Pendiente: ${esc(i.open_balance)} · ${esc(statusLabel(i.status))}</p>${i.applications.map(a=>`<p>${esc(a.posting_date)} · ${esc(a.amount)} · ${a.is_effective?'Aplicado':'Sin efecto a esta fecha'} <button class="linkbutton" data-reverse="${a.entry_id}">Revertir este cobro/pago</button></p>`).join('')}`;bindReversals($('itemDetails'))}catch(e){showError('subledgerError',e)}}
$('confirmReversal').onclick=async()=>{try{await api('/api/operations/'+subledgerState.reversalEntry+'/reverse',{method:'POST',body:JSON.stringify({reason:$('reversalReason').value,reversal_date:$('reversalDate').value})});$('reversalForm').classList.add('hidden');$('itemDetails').textContent='Operación revertida. Consulta las obligaciones a la fecha de reversión para observar la reapertura.';await loadItems();await loadRecent()}catch(e){showError('subledgerError',e)}};
$('cancelReversal').onclick=()=>$('reversalForm').classList.add('hidden');
$('inspectItem').onclick=async()=>{try{const v=await api('/api/subledger/open-items/'+encodeURIComponent($('proItemId').value)+'/professional?as_of='+$('proAsOf').value);const i=v.open_item;$('proItemOutput').innerHTML=`<h3>${esc(i.third_party_name)} · ${esc(i.document_number)}</h3><p>Origen: póliza ${i.source_entry_id}, línea ${i.source_line_id}. Vence ${esc(i.due_date)}. Aging: ${esc(i.aging_bucket)}. Estado: ${esc(i.status)}.</p><p>Original ${esc(i.original_amount)} · Aplicado ${esc(i.applied_amount)} · Abierto ${esc(i.open_balance)}</p><h3>Origen, aplicaciones, documentos, reversión y auditoría</h3><pre>${esc(JSON.stringify(v,null,2))}</pre>${i.applications.map(a=>`<button class="linkbutton" data-reverse="${a.entry_id}">Revertir póliza de aplicación ${a.entry_id}</button>`).join(' ')}`;bindReversals($('proItemOutput'))}catch(e){showError('professionalError',e)}};
$('reconcileButton').onclick=async()=>{try{const r=await api('/api/subledger/reconciliation/'+$('proKind').value+'?as_of='+$('proAsOf').value);$('reconcileOutput').textContent=JSON.stringify(r,null,2)}catch(e){showError('professionalError',e)}};
$('refreshItems').onclick=loadItems;$('itemKind').onchange=loadItems;
async function initSubledger(){const today=new Date().toISOString().slice(0,10);['creditDate','creditDocumentDate','dueDate','itemDate','paymentDate','paymentDocumentDate','reversalDate','proAsOf'].forEach(id=>$(id).value=today);await loadParties();await loadItems()}
initSubledger().catch(e=>showError('subledgerError',e));
</script>
</body></html>'''

__all__ = ["APP_HTML"]
